export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const USER_TO_STATE = "USER_TO_STATE";
export const TAPS_TO_STATE = "TAPS_TO_STATE";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const LOCATION_TO_STATE = "LOCATION_TO_STATE";